---
title: "Transition management"
output:
  github_document:
    toc: true
    toc_depth: 1
editor_options: 
  chunk_output_type: inline
---

The goal of the current course is to gain insights in the uniqueness of the transition dairy cow. 

# Introduction

## The teacher

This first session will introduce Miel Hostens as teacher for the different sessions.

<iframe src="https://www.youtube.com/embed/bT79VMQOnrs" frameborder="0" allowfullscreen="true"> </iframe>

[Link to the raw presentation](https://prezi.com/view/eOCdI7EIZmOEwEQP6lG4/)

<iframe width="400" height="250" src="https://www.youtube.com/embed/bT79VMQOnrs">&nbsp;</iframe>

## The industry

This session will focus on a broader and general introduction to the dairy industry as we know it today.

The poll which you are requested to fill in is [here](https://www.menti.com/jp3kenbmz7)

[Link to the raw presentation](https://prezi.com/view/fhX2xHhhiYPfEn76McCe/)

<iframe width="400" height="250" 
src="https://www.youtube.com/embed/VqvdjKvdBDk" 
frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<iframe width="400" height="250" 
src="https://www.youtube.com/embed/Ey5UNYJ9ZRM" 
frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

# The unique transition dairy cow

## Physiology

The course starts with the basic physiology of the dairy cow.

[Link to the raw presentation](https://prezi.com/view/v2KDzmGQYWlFd7iFpljO/) and a [link to literature cited](1_Physiology/Literature/)

<iframe width="400" height="250" 
src="https://www.youtube.com/embed/pgrZpJBpseE" 
frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

## Energy metabolism

[Link to the raw presentation](https://prezi.com/view/eOCdI7EIZmOEwEQP6lG4/) and a [link to literature cited](2_EnergyMetabolism/Literature/)

<iframe width="400" height="250" 
src="https://www.youtube.com/embed/D_fpTZ06tXU" 
frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<iframe width="400" height="250" 
src="https://www.youtube.com/embed/7ri6sRG4d8I" 
frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

# Transition disease and its short and long term effects

# Housing the transition dairy cow

# Feeding the transition dairy cow

# Monitoring the transition dairy cow

# Treating the transition dairy cow

## Hypocalcemia & downer cows

## Ketosis

## Retained placenta

## Metritis

## Abomasal displacement

